export const STRINGS = {
  FEEFO_SUPPORT_CONTACT: "YOUR FEEFO SUPPORT CONTACT",
  SUPPORT: "Support",
  SUPPORT_NUMBER: "020 3363 4208",
  YOU_HAD: `You had`,
  UPLOADS: "uploads",
  AND: "and",
  LINES_ADD: "lines added.",
  SALES: "Sales",
  UPLOAD_SUCCESS: "UPLOAD SUCCESS",
  LINES_SAVED: "LINES SAVED",
};
